name: Issue Trigger
on:
  issues:
    types: [opened, transferred, assigned, labeled, unlabeled]

jobs:
  # Adds missing labels to newly-created or transferred issues
  Add-Missing-Labels-To-Issues:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'opened' || github.event.action == 'transferred' }}
    steps:
      - uses: actions/checkout@v4    
      # Check if the issue has required labels
      - name: Check Labels
        id: check-labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.HACKFORLA_GRAPHQL_TOKEN }}
          script: |
            const script = require('./github-actions/trigger-issue/add-missing-labels-to-issues/check-labels.js')
            const checkLabels = script({g: github, c: context})
            return checkLabels
          
